# Generated by Django 2.2 on 2020-01-21 14:31

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GPB', 'GPB')], help_text='Код базовой валюты конвертирования по ISO', max_length=3, verbose_name='Базовая валюта конвертирования')),
                ('rates', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON с курсами валют', verbose_name='JSON с курсами валют')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи о курсах валют', verbose_name='Дата и время создания записи о курсах валют')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GPB', 'GPB')], help_text='Код валюты по ISO', max_length=3, verbose_name='Валюта кошелька')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Текущий баланс кошелька, ограничение в 1 млрд', max_digits=11, verbose_name='Баланс кошелька')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания кошелька', verbose_name='Дата и время создания кошелька')),
                ('is_active', models.BooleanField(default=True, help_text='Активен', verbose_name='Активен')),
                ('owner', models.ForeignKey(help_text='Владелец кошелька', on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кошелька')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Ограничение в 1 млрд', max_digits=11, verbose_name='Сумма перевода')),
                ('exchange_rate', models.DecimalField(decimal_places=5, default=Decimal('1'), help_text='Обменный курс на момент транзакции', max_digits=10, verbose_name='Обменный курс на момент транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи о переводе', verbose_name='Дата и время создания записи о переводе')),
                ('recipient', models.ForeignKey(help_text='Кошелёк получателя', on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_recipient', to='wallet.Wallet', verbose_name='Кошелёк получателя')),
                ('sender', models.ForeignKey(help_text='Кошелёк отправителя', on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_sender', to='wallet.Wallet', verbose_name='Кошелёк отправителя')),
            ],
        ),
    ]
