# Generated by Django 2.2 on 2020-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP')], help_text='Код базовой валюты конвертирования по ISO', max_length=3, verbose_name='Базовая валюта конвертирования'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP')], help_text='Код валюты по ISO', max_length=3, verbose_name='Валюта кошелька'),
        ),
    ]
